GET localhost:8080/users

###

POST localhost:8080/users
Content-Type: application/json

{
  "name": "blabla",
  "age": 10,
  "countryOfResidence": "Warsaw"
}

###

GET localhost:8080/users

###

POST localhost:8080/users
Content-Type: application/json

{
  "name": "blabla2",
  "age": 10,
  "countryOfResidence": "Warsaw"
}
###

GET localhost:8080/users

###
GET localhost:8080/users/67729e84-9f4b-403f-9723-3fe2d692a5e6

###
DELETE localhost:8080/users/abc

###
GET localhost:8080/users
